language: cpp

branches:
  only:
   - master

dist: focal

addons:
  apt:
    packages:
      - lcov

os:
  - linux

compiler:
  - gcc

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
